# docker-compose.yml
version: '3.10'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:80
    image: app:mydjangoappnewaws
    container_name: mydjangoappnewaws_container2
  
    command: python manage.py runserver 0.0.0.0:80
    restart: always
    volumes:
      - .:/mydjangoappnewaws
    networks:
      - djangonetworknewaws
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    restart: always
    ports:
      - 7406:3306
    environment:
      MYSQL_DATABASE: django-app-db
#      MYSQL_PASSWORD: myLocalAdminPassRoot22
      MYSQL_ROOT_PASSWORD: myLocalAdminPassRoot22
    networks:
      - djangonetworknewaws
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8059:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: myLocalAdminPassRoot22
    networks:
      - djangonetworknew
networks:
  djangonetworknew:
volumes:
  db:
